/* eslint-disable @next/next/no-img-element */
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const BASE_URL = "http://localhost:3000";
  const [pokemons, setPokemons] = useState<any[]>([]);

  useEffect(() => {
    async function fetchData() {
      const response = await fetch(`${BASE_URL}/pokemons.json`);
      setPokemons(await response.json());
    }

    fetchData();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Pokemon List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.grid}>
        {pokemons?.map((pokemon) => (
          <div className={styles.card} key={pokemon.id}>
            <Link href="/pokemon/[id]" as={`/pokemon/${pokemon.id}`}>
              <a>
                <img src={`${BASE_URL}/${pokemon.image}`} alt={pokemon.name} />
              </a>
            </Link>
          </div>
        ))}
      </div>
    </div>
  );
};

export default Home;
